## Paperclip Options
## 
## This hash will be passed to Myfile#has_attached_file
##
## See http://dev.thoughtbot.com/paperclip/classes/Paperclip/ClassMethods.html
## for additional has_attached_file options
all:
  path: ":rails_root/uploads/:id"
  url: "/assets/:style/:id_:basename.:extension"
  default_style: original
  processors: 
    - text_search
  styles:                                         # <--- Necessary to trigger processors
    :original: {}              
  
  #path: ":upload_path/:style/:id"                  <--- Uncomment to use multiple styles
  #styles:
  #  preview: '100x80#'

  ## See http://dev.thoughtbot.com/paperclip/classes/Paperclip/Storage/S3.html
  ## for additional S3 Options    
  #storage: s3                                      <--- Uncomment to use Amazon S3 for storage
  #s3_credentials:
  # access_key_id: 123...
  # secret_access_key: 123...
  #bucket: <mybucket>                               <--- Change to your bucket name


## If you'd like to change the paperclip options based
## on the environment, just add the options you'd like to
## use under the environment - these settings will be added
## and over-write any existing ones
#production:
#  storage: s3                                      <--- Uncomment to use Amazon S3 for storage
#  s3_credentials:
#   access_key_id: 123...
#   secret_access_key: 123...
#  bucket: <mybucket>                               <--- Change to your bucket name
