--- !map:HashWithIndifferentAccess

development:
  ## Using ferret
  #searcher: acts_as_ferret
  #folder_args:
  #  fields:
  #    - name
  #file_args:
  #  fields: 
  #    - text
  #    - attachment_file_name
  #search_signature: find_by_tsearch
  ## specifies a gem to be loaded for the searcher
  #require: acts_as_ferret
    
  ## Using Postgres
  ## tsearch requires a search index in the database, so 
  ## be sure to uncomment this line before migrating your
  ## database (or re migrate it with this uncommented)
  searcher: index
  folder_block:
    name: 
  file_block:
    text: B
    attachment_file_name: A
  search_signature: search
  
test:
  # No searching defined


production:
  # Same as above...
  
  #searcher: acts_as_ferret
